export const PROFESSIONS = {
  "Antiquarian": {
    key: "Antiquarian",
    title: "古董收藏家",
    skills: ["历史", "艺术"],
    creditRating: "30-70",
    skillPoints: "EDU × 4",
    description: "我是一位专注于历史文物研究的专家。凭借深厚的历史知识和艺术鉴赏能力,我能准确评估和分析各类古董文物的价值与历史意义。",
  },
  "Artist": {
    key: "Artist",
    title: "艺术家",
    skills: ["艺术", "巧手"],
    creditRating: "9-50", 
    skillPoints: "EDU × 2 + LUCK × 2",
    description: "我是一位追求艺术完美的创作者。我灵巧的双手能将灵感转化为触动人心的艺术品,同时也善于通过作品与人交流。",
  },
  "Clergy": {
    key: "Clergy",
    title: "神父",
    skills: ["神秘学", "交际", "心理学"],
    creditRating: "9-60",
    skillPoints: "EDU × 4",
    description: "我是一位虔诚的信仰传播者。通过对神秘学的研究、出色的交际能力和对人性的深刻理解,我引导着信徒寻找精神慰藉。",
  },
  "Criminal": {
    key: "Criminal",
    title: "罪犯",
    skills: ["巧手", "枪械", "格斗", "闪避"],
    creditRating: "5-65",
    skillPoints: "EDU × 2 + DEX × 2",
    description: "我是游走在法律边缘的暗影人物。精通巧手技巧和各类武器,在危险时刻总能依靠灵活的身手脱身。",
  },
  "Doctor": {
    key: "Doctor",
    title: "医生",
    skills: ["医学", "巧手", "科学"],
    creditRating: "30-80",
    skillPoints: "EDU × 4",
    description: "我是一位专业的医学工作者。依靠扎实的医学知识、灵巧的手术技能和科学的思维方式,我致力于治愈病患、拯救生命。",
  },
  "Engineer": {
    key: "Engineer",
    title: "工程师",
    skills: ["机械", "科学", "电子"],
    creditRating: "30-60",
    skillPoints: "EDU × 4",
    description: "我是一位精通技术的问题解决者。凭借对机械、科学和电子领域的深入理解,我能设计、建造和修复各种复杂系统。",
  },
  "Performer": {
    key: "Performer",
    title: "艺人",
    skills: ["交际", "心理学", "艺术"],
    creditRating: "9-70",
    skillPoints: "EDU × 2 + APP × 2",
    description: "我是一位舞台上的表演大师。通过对人性的洞察和精湛的艺术表现力,我能在各种场合赢得观众的喝彩。",
  },
  "Farmer": {
    key: "Farmer",
    title: "农场主",
    skills: ["枪械", "驾驶", "交际", "侦查"],
    creditRating: "9-30",
    skillPoints: "DEX × 2 + STR × 2",
    description: "我是一位经验丰富的农场经营者。精通农机驾驶和维护,善于观察天气变化,也懂得与人打交道。必要时,我也能用枪保护自己的财产。",
  },
  "Hacker": {
    key: "Hacker",
    title: "黑客",
    skills: ["电子", "侦查"],
    creditRating: "10-70",
    skillPoints: "EDU × 4",
    description: "我是一位数字世界的探索者。通过精湛的电子技术和敏锐的观察力,我能深入任何数字系统的核心。",
  },
  "Journalist": {
    key: "Journalist",
    title: "记者",
    skills: ["交际", "心理学", "侦查"],
    creditRating: "9-30",
    skillPoints: "EDU × 4",
    description: "我是一位追寻真相的新闻工作者。凭借出色的交际能力、对人性的洞察和细致的调查技巧,我致力于还原每一个事件的真相。",
  },
  "Lawyer": {
    key: "Lawyer",
    title: "律师",
    skills: ["交际", "图书馆使用", "心理学"],
    creditRating: "30-80",
    skillPoints: "EDU × 4",
    description: "我是一位精通法律的辩护者。通过丰富的法律知识、出色的交际能力和对人性的理解,我为当事人争取最大的法律权益。",
  },
  "Librarian": {
    key: "Librarian",
    title: "图书馆管理员",
    skills: ["图书馆使用", "科学", "神秘学"],
    creditRating: "9-35",
    skillPoints: "EDU × 4",
    description: "我是一位知识的守护者和引路人。精通图书分类和检索,对科学和神秘学都有深入研究,能帮助人们找到他们需要的任何信息。",
  },
  "Officer": {
    key: "Officer",
    title: "军官",
    skills: ["交际", "枪械", "心理学"],
    creditRating: "20-70",
    skillPoints: "EDU × 2 + DEX × 2",
    description: "我是一位经验丰富的军事指挥官。精通枪械使用,善于领导和激励部下,能准确把握战场局势和人员心理。",
  },
  "Zealot": {
    key: "Zealot",
    title: "邪教徒",
    skills: ["神秘学", "心理学", "闪避"],
    creditRating: "0-70",
    skillPoints: "EDU × 2 + POW × 2",
    description: "我是一位狂热的信仰追随者。深谙神秘学知识,善于洞察和影响他人心理,在危险时刻总能化险为夷。",
  },
  "Detective": {
    key: "Detective",
    title: "警探",
    skills: ["侦查", "心理学", "枪械", "交际"],
    creditRating: "20-50",
    skillPoints: "EDU × 2 + STR × 2",
    description: "我是一位专业的刑事侦查员。凭借敏锐的洞察力、对犯罪心理的理解和丰富的办案经验,我能破解各种复杂案件。",
  },
  "PoliceOfficer": {
    key: "PoliceOfficer",
    title: "警察",
    skills: ["驾驶", "枪械", "格斗"],
    creditRating: "9-30",
    skillPoints: "POW × 2 + STR × 2",
    description: "我是一位尽职的治安维护者。精通驾驶和各类武器使用,在紧急情况下能迅速反应并处理各种突发事件。",
  },
  "PrivateInvestigator": {
    key: "PrivateInvestigator",
    title: "私家侦探",
    skills: ["侦查", "潜行", "交际", "心理学"],
    creditRating: "9-30",
    skillPoints: "EDU × 2 + DEX × 2",
    description: "我是一位独立的真相探寻者。通过细致的观察、隐秘的跟踪和巧妙的交谈,我能发现并揭示各种隐藏的秘密。",
  },
  "Professor": {
    key: "Professor",
    title: "教授",
    skills: ["图书馆使用", "心理学"],
    creditRating: "20-70",
    skillPoints: "EDU × 4",
    description: "我是一位博学多才的学者。精通文献检索,深谙教育心理学,在我的专业领域具有独到的见解和研究成果。",
  },
  "Soldier": {
    key: "Soldier",
    title: "士兵",
    skills: ["格斗", "闪避", "枪械"],
    creditRating: "9-30",
    skillPoints: "POW × 2 + STR × 2",
    description: "我是一位训练有素的战士。精通各种战斗技能,面对危险时能迅速反应并作出正确判断。",
  },
  "TribalMember": {
    key: "TribalMember",
    title: "部落成员",
    skills: ["神秘学", "侦查", "格斗"],
    creditRating: "0-15",
    skillPoints: "EDU × 2 + LUCK × 2",
    description: "我是一位与自然紧密相连的部落成员。精通古老的神秘仪式,具备敏锐的观察力和出色的生存技能。",
  },
};